config:
  info: "This is a demo   Update Again Update To Again Update Twice Update 22222 Test Spring Bus Advice Before have a question is management endpoints web exposure include is bus refresh but curl don't support POST command change * later can curl"
