config:
  info: "This is a demo   Update Again Update To Again Update Twice Update 22222 Test Spring Bus Advice Before have a question is management endpoints web exposure include is bus refresh but curl don't support POST command change * later can curl   
      Send notification to the specified configuration client. Command is curl -X POST http://localhost:3344/actuator/bus-refresh/config-client:3355
      xiugai
  "
